version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 50
    target-branch: 'main'
    ignore:
      # For all deps
      - dependency-name: "*"
      # ignore all major updates
      update-types: ["version-update:semver-major"]

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 50
    target-branch: 'main'
